#Provide the workflow engine configuration details here

#TYPE = Exetrnal workflow engine type
#ENGINE_URL = External workflow engine url 
[workflow_engine_config]
TYPE = "camunda"
ENGINE_URL = "http://localhost:8080/engine-rest/process-definition"

#Provide the callback configuration details here
[callbackconfig]
CALLBACK_END_POINT = "http://localhost:9763/api/server/v1/workflow/"


